import {AddOrder,getOrder,getOrderSingle,getMemberTotal,cancelbuy} from '@/plugins/api';
import {API} from '@/plugins/axios';
export const state = () =>({
    orderList:[
    ],
    orderListBak:[
    ],
    order_m:[],
    prodname:'',
    price:0,
    username:'',
    status:'',
    key_word:'',
    //API
    username:'',
    email:'',
    phone:'',
    orderNotes:'',
    deliver_name:'',
    deliver_phone:'',
    pay_method:'',
    notes:'',
    location:'',
    delivermethods:'',
    memberOrder:0
});
export const actions ={
    setdata({commit},data){
        commit('Setdata',data)
    },
    addorder({commit},data){
        commit('Addorder',data)
    },
    getdata({commit},data){
        commit('Getdata',data)
    },
    editdata({commit},data){
        commit('Editdata',data)
    },
    removedata({commit},data){
        commit('Removedata',data)
    },
    searchitem({commit},data){
        commit('Searchitem',data)
    },
    allitem({commit}){
        commit('Allitem')
    },
    //API
    //拿會員所有訂單
    getOrder({commit},data){
        API('get','Order',data).then((res)=>{
            // console.log(res.data)
            commit('ReflashOrder',res.data)
        })
    },
    //拿會員單一筆訂單主檔
    getOrderSingle({commit},data){
        API('get',`Order/getSingle/${data}`).then((res)=>{
            commit('ReflashOrder_m',res.data)
        })
    },
    //拿會員至今消費總額
    getTotal({commit},data){
        API('get',`Order/getMemberTotal/${data}`).then((res)=>{
            commit('setNowTotal',res.data)
        })
    },
    //取消購買
    cancelPurchase({commit},data){
        API('delete',`Order/${data}`).then((res)=>{
            commit('ReflashOrder',res.data)
        })
    },
};

export const mutations ={
    Setdata(state,data){
        state.prodname=data.prodname,
        state.price=data.price,
        state.username=data.username,
        state.status=data.status
    },
    Addorder(state,data){
        state.orderList.push(data);
    },
    Getdata(state,data){
        state.prodname=state.orderList[data].prodname
        state.price=state.orderList[data].price
        state.username=state.orderList[data].username
        state.status=state.orderList[data].status
    },
    Editdata(state,data){
        let i = data.index;
        state.orderList[i].prodname=data.prodname;
        state.orderList[i].price=data.price;
        state.orderList[i].username=data.username;
        state.orderList[i].status=data.status;
    },
    Removedata(state,data){
        state.orderList.splice(data,1)
    },
    Allitem(state){
        state.orderList=state.orderListBak;
    },
    Searchitem(state,data){
        state.key_word=data;
        state.orderList=state.orderListBak;
        state.orderList=state.orderList.filter(item=>item.prodname.toLowerCase().match(data));
    },
    setprodname(state,val){
        state.prodname=val;
    },
    setprice(state,val){
        state.price=val;
    },
    setusername(state,val){
        state.username=val;
    },
    setstatus(state,val){
        state.status=val;
    },
    setemail(state,val){
        state.email=val;
    },
    setusername(state,val){
        state.username=val;
    },
    setphone(state,val){
        state.phone=val;
    },
    setPaymethod(state,val){
        state.pay_method=val;
    },
    setLocation(state,val){
        state.location=val;
    },
    setDelivermethods(state,val){
        state.delivermethods=val;
    },
    setNotes(state,val){
        state.notes=val;
    },
    setUserdata(state,val){
        state.username=val.username;
        state.phone=val.phone;
        state.email=val.email;
    },
    //API
    ReflashOrder(state,val){
        state.orderList = val
    },
    ReflashOrder_m(state,val){
        state.order_m = val
    },
    setNowTotal(state,val){
        state.memberOrder=val;
    }
};

export const getters ={
    
};