export const state = () =>({
    products:[
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
    ],
    productsBak:[
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
        {name:'玉米蛋餅',price:45,sale:5},
        {name:'蘑菇麵+蛋',price:50,sale:5},
        {name:'營養早餐',price:45,sale:0},
        {name:'里肌總匯',price:45,sale:0},
        {name:'抓餅加蛋',price:40,sale:20},
        {name:'煎餃',price:40,sale:10},
        {name:'蘿蔔糕',price:40,sale:10},
        {name:'厚切牛肉堡',price:70,sale:0},
        {name:'果醬厚片',price:25,sale:0},
        {name:'大冰奶',price:30,sale:5},
    ],
    name:'',
    price:0,
    sale:0,
    key_word:''
});

export const actions ={
    changeproduct({commit},item){
        commit('Changeproduct',item)
    },
    searchitem({commit},data){
        commit('Searchitem',data)
    },
    allitem({commit}){
        commit('Allitem')
    },
    getdata({commit},data){
        commit('Getdata',data)
    },
    editdata({commit},data){
        commit('Editdata',data)
    },
    removedata({commit},data){
        commit('Removedata',data)
    },
    adddata({commit},data){
        commit('Adddata',data)
    }
};

export const mutations ={
    Changeproduct(state,item){
        state.name=item.name
        state.price=item.price
        state.sale=item.sale
    },
    Searchitem(state,data){
        state.key_word=data;
        state.products=state.productsBak;
        state.products=state.products.filter(item=>item.name.match(data));
    },
    Allitem(state){
        state.products=state.productsBak;
    },
    Getdata(state,data){
        state.name=state.products[data].name
        state.price=state.products[data].price
        state.sale=state.products[data].sale
    },
    Editdata(state,data){
        let i = data.index;
        state.products[i].name=data.name;
        state.products[i].price=data.price;
        state.products[i].sale=data.sale;
    },
    Removedata(state,data){
        state.products.splice(data,1)
    },
    Adddata(state,data){
        state.products.push(data)
    },
    setname(state,val){
        state.name=val;
    },
    setprice(state,val){
        state.price=val;
    },
    setsale(state,val){
        state.sale=val;
    }
};

export const getters ={
};